# Use a lighter version of Node as a parent image
FROM node:alpine3.12
# Set the working directory to /client
WORKDIR /app-ui
# copy package.json into the container at /client
COPY package*.json /app-ui/

RUN CI=true
# install dependencies
RUN npm install
# Copy the current directory contents into the container at /client
COPY . /app-ui/
# Make port 3000 available to the world outside this container
EXPOSE 3000
# Run the app when the container launches
CMD ["npm", "start"]